slug: ya-zi-wang-guo
name: 鸭子王国
style: custom
style_prompt: 使用浅黄色 / 红褐色的水彩画风格，走可爱卡通路线，主要角色是一只黄色的可爱的鸭子，类似 motherduck 的风格
style_reference_image: style_reference.jpg
created_at: '2026-04-02T23:29:28.436479Z'
