import { Agent } from 'simple-agent';
import { BashTool, ReadTool, WriteTool } from 'simple-agent';
import { readFileSync, mkdirSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { config } from 'dotenv';

config({ override: false });

function escapeHtml(text: string): string {
  const map: Record<string, string> = {
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;'
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}

const args = process.argv.slice(2);

if (args.includes('--help') || args.includes('-h')) {
  console.log(`Usage: code-review-agent "<自然语言描述要 review 的内容>"
Example: code-review-agent "review PR 12"
         code-review-agent "review 当前 branch 新代码"
         code-review-agent "review commit 13bad5 之后的代码"`);
  process.exit(0);
}

const apiKey = process.env.OPENAI_API_KEY || process.env.ANTHROPIC_API_KEY;
if (!apiKey) {
  console.error('Error: API key required. Set OPENAI_API_KEY or ANTHROPIC_API_KEY');
  process.exit(1);
}

const userInput = args.join(' ');
if (!userInput) {
  console.error('Usage: code-review-agent "<自然语言描述要 review 的内容>"');
  console.error('Example: code-review-agent "review PR 12"');
  process.exit(1);
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const basePath = process.cwd();

let systemPrompt = '';
try {
  systemPrompt = readFileSync(join(basePath, 'prompts/system.md'), 'utf-8');
} catch {
  console.error('Error: prompts/system.md not found');
  process.exit(1);
}

try {
  mkdirSync(join(basePath, 'reviews'), { recursive: true });
} catch (e) {
  console.warn('[Warning] Could not create reviews directory:', e);
}

const envProvider = process.env.PROVIDER;
const validProviders = ['openai', 'anthropic'];
const provider = envProvider && validProviders.includes(envProvider)
  ? envProvider as 'openai' | 'anthropic'
  : 'openai';

const model = process.env.MODEL || 'gpt-4o';
const baseURL = process.env.ANTHROPIC_BASE_URL || process.env.OPENAI_BASE_URL;

const agentConfig: {
  provider: 'openai' | 'anthropic';
  model: string;
  apiKey: string;
  baseURL?: string;
} = {
  provider,
  model,
  apiKey,
};

if (baseURL) {
  agentConfig.baseURL = baseURL;
}

const agent = new Agent(agentConfig);
agent.registerTools([new BashTool(), new ReadTool(), new WriteTool()]);

const messages = [
  { role: 'system' as const, content: systemPrompt },
  { role: 'user' as const, content: userInput },
];

const outputBuffer: string[] = [];
const date = new Date().toISOString().split('T')[0];
const reportFileName = join(basePath, `reviews/${date}-review-report.md`);

console.log('[Code Review Agent] Starting...\n');

{
  let iter;
  try {
    iter = agent.run(messages, 'loop');
  } catch (e) {
    console.error('[Fatal]', e);
    process.exit(1);
  }

  try {
    for await (const result of iter) {
      switch (result.type) {
        case 'message':
          if (result.content) {
            console.log(result.content);
            outputBuffer.push(result.content);
          }
          break;
        case 'tool-call':
          console.log(`[Tool] ${result.metadata?.toolName || 'unknown'}`);
          outputBuffer.push(`\n[Tool] ${result.metadata?.toolName || 'unknown'}`);
          break;
        case 'tool-result':
          const content = result.content || '';
          console.log(`[Result] ${content.slice(0, 200)}${content.length > 200 ? '...' : ''}`);
          outputBuffer.push(`[Result] ${content}`);
          break;
        case 'done':
          console.log('\n[Done] Review completed');
          if (outputBuffer.length > 0) {
            const reportContent = `# Code Review Report

**审查时间**: ${date}
**用户输入**: ${escapeHtml(userInput)}

---

${outputBuffer.map(line => escapeHtml(line)).join('\n\n')}

---
*Generated by Code Review Agent*
`;
            try {
              writeFileSync(reportFileName, reportContent, 'utf-8');
              console.log(`\n[Report] Saved to ${reportFileName}`);
            } catch (e) {
              console.warn('[Warning] Could not save report file');
            }
          }
          break;
        case 'error':
          console.error('[Error]', result.content);
          break;
        }
    }
  } catch (e) {
    console.error('[Fatal]', e);
    process.exit(1);
  }
}
